# Generated by Django 5.2.8 on 2026-08-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_failure_code_payment_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Razorpay fee on this payment, INCLUDING the GST on it. 0 = not reported yet (no webhook/reconcile has supplied it).', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST portion of gateway_fee — input tax credit, deductible from output tax. Contained in gateway_fee, not added to it.', max_digits=10),
        ),
    ]
