# Generated by Django 5.2.8 on 2026-07-22 09:19

import spices_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[spices_backend.validators.validate_file_size, spices_backend.validators.validate_image_extension, spices_backend.validators.validate_image_content]),
        ),
    ]
