# Generated by Django 5.2.8 on 2026-10-01 10:18
# AP5: grandfathering appended by hand in the SAME new file (older migrations
# untouched). Owner decision §7.1 can flip this to "verify everyone".

from django.db import migrations, models


def grandfather_verified(apps, schema_editor):
    """Mark emails as verified where ownership was already proven in practice.

    - Users with a DELIVERED order paid/placed with that address (they received
      goods and order emails there).
    - Google-created rows: unusable password + a login on record (Google only
      lets the flow complete for a verified inbox).

    Everyone else starts unverified and confirms once via
    POST /api/auth/verify-email/ (OTP at registration, or resend).
    """
    User = apps.get_model('users', 'User')
    Order = apps.get_model('orders', 'Order')
    delivered_ids = (
        Order.objects.filter(status='delivered').values_list('user_id', flat=True).distinct()
    )
    User.objects.filter(pk__in=delivered_ids, email_verified=False).update(email_verified=True)
    # Unusable passwords ALWAYS start with '!' regardless of PASSWORD_HASHERS
    # (see django.contrib.auth.hashers.UNUSABLE_PASSWORD_PREFIX), so this is
    # hasher-agnostic: last_login + no usable password == signed in via Google.
    User.objects.filter(
        email_verified=False,
        last_login__isnull=False,
        password__startswith='!',
    ).update(email_verified=True)


def ungrandfather(apps, schema_editor):
    # Reverse migration: clear only what this migration set is not knowable, so
    # reset the flag wholesale (re-running the forward pass restores it).
    apps.get_model('users', 'User').objects.update(email_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile_picture'),
        ('orders', '0023_order_courier_name_order_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(grandfather_verified, ungrandfather),
    ]
