# Generated by Django 5.2.8 on 2026-07-19 10:30

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_deleted_at_order_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_bill',
            field=models.FileField(blank=True, help_text='Admin-only courier/delivery receipt. Never shown to customers.', null=True, storage=orders.models.delivery_bill_storage, upload_to=orders.models.delivery_bill_upload_path),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_bill_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
