# Generated by Django 5.2.8 on 2026-07-31 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_tax_inclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual courier cost for this order (admin-entered, ₹0 = not recorded). ADMIN-ONLY — never expose to customers.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST %% applied to this line at order time (snapshot).', max_digits=5),
        ),
    ]
