# Generated by Django 5.2.8 on 2026-07-31 14:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_shipping_cost_item_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total money returned to the customer across all refunds.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When the MOST RECENT refund was recorded. Per-refund dates live on OrderRefund — reporting attributes GST reversal by those.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST reversed by those refunds. SUBTRACTED from GST collected when reporting what is owed to the government.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('delivering', 'Delivering'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Money returned to the customer in this refund (GST-inclusive).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='GST contained in `amount` — the output tax this refund reverses.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('gateway', 'Gateway webhook'), ('admin', 'Recorded by admin')], default='gateway', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_089263_idx')],
            },
        ),
    ]
