# Generated by Django 5.2.8 on 2026-08-03 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_stock_restored_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_confirmed_by',
            field=models.ForeignKey(blank=True, help_text="Admin who ticked 'Paid in cash'. Recorded because confirming receipt of cash is the highest-trust action in the panel.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cod_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_paid_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When an admin confirmed the COD cash was received. NULL on a COD order means the money is still outstanding.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST charged on the delivery fee, ADDED on top of shipping_charge. 0 on free-shipping orders and on orders placed before delivery was taxed.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST on the GOODS at the discounted amount. When tax_inclusive is True this is CONTAINED IN subtotal (disclosure only); on legacy orders it was ADDED to reach total_amount. Does NOT include GST on delivery — see shipping_tax, and use total_tax to report both.', max_digits=10),
        ),
    ]
