# Generated by Django 5.2.8 on 2026-10-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_dailysalesrollup_cod_collected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'Product View'), ('click', 'Product Click'), ('add_to_cart', 'Add To Cart'), ('remove_from_cart', 'Remove From Cart'), ('favorite', 'Favorite'), ('search', 'Search'), ('purchase', 'Purchase'), ('page_view', 'Page View'), ('checkout_started', 'Checkout Started'), ('checkout_completed', 'Checkout Completed'), ('checkout_abandoned', 'Checkout Abandoned'), ('voice_used', 'Voice Input Used'), ('voice_confirmed', 'Voice Proposal Confirmed')], max_length=20),
        ),
    ]
