# Generated by Django 5.2.8 on 2026-07-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_fix_chaat_masala_spelling_retry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSlugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_aliases', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product slug aliases',
            },
        ),
    ]
