# Generated by Django 5.2.8 on 2026-07-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_seed_retired_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_categories',
            field=models.ManyToManyField(blank=True, help_text='Also list this product under these categories.', related_name='extra_products', to='products.category'),
        ),
    ]
