# Generated by Django 5.2.8 on 2026-07-22 09:19

import spices_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[spices_backend.validators.validate_file_size, spices_backend.validators.validate_image_extension, spices_backend.validators.validate_image_content]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[spices_backend.validators.validate_file_size, spices_backend.validators.validate_image_extension, spices_backend.validators.validate_image_content]),
        ),
        migrations.AlterField(
            model_name='productcombo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combos/', validators=[spices_backend.validators.validate_file_size, spices_backend.validators.validate_image_extension, spices_backend.validators.validate_image_content]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', validators=[spices_backend.validators.validate_file_size, spices_backend.validators.validate_image_extension, spices_backend.validators.validate_image_content]),
        ),
    ]
