# Generated by Django 5.2.8 on 2026-07-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert the admin when this size falls to or below this stock level.'),
        ),
    ]
