# Generated by Django 5.2.8 on 2026-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_productcombo_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productcombo',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'deactivated_at'], name='products_pr_is_acti_618229_idx'),
        ),
        migrations.AddIndex(
            model_name='productcombo',
            index=models.Index(fields=['is_active', 'deactivated_at'], name='products_pr_is_acti_c2e7ad_idx'),
        ),
    ]
