# Generated by Django 5.2.8 on 2026-08-03 23:04

import products.hsn
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_combo_derived_mrp_drop_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, default='', help_text='HSN code (4, 6 or 8 digits) for GST returns. Leave blank if not yet classified.', max_length=8, validators=[products.hsn.validate_hsn_code]),
        ),
    ]
