# Generated by Django 5.2.8 on 2026-10-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_papad_masala_taxable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetachedComboLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('combo_was_active', models.BooleanField(default=False)),
                ('detached_at', models.DateTimeField(auto_now_add=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detached_lines', to='products.productcombo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detached_combo_lines', to='products.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.productvariant')),
            ],
            options={
                'unique_together': {('combo', 'variant')},
            },
        ),
    ]
