# Generated by Django 5.2.8 on 2026-07-10 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_refresh_privacy_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='If set, only this customer can use the coupon.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Flat ₹ off — used when discount_type='fixed'", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount (₹)')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, help_text="Discount percentage (1-100) — used when discount_type='percent'", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
