# Generated by Django 5.2.8 on 2026-07-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dailysalesrollup_alter_userevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalesrollup',
            name='gst_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailysalesrollup',
            name='shipping_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailysalesrollup',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
