# Generated by Django 5.2.8 on 2026-07-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_sales_rollup_gst_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalesrollup',
            name='gst_refunded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailysalesrollup',
            name='refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
