# Generated by Django 5.2.8 on 2026-08-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_rollup_refunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalesrollup',
            name='cod_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailysalesrollup',
            name='shipping_tax_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
