# Generated by Django 5.2.8 on 2026-08-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this review in the home page testimonials strip.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title_gu',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title_hi',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title_hinglish',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title_mr',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title_pa',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
