# Generated by Django 5.2.8 on 2026-10-01 09:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_update_seller_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('raw_material', 'Raw material / purchases'), ('packaging', 'Packaging'), ('marketing', 'Marketing'), ('rent_utilities', 'Rent & utilities'), ('salary', 'Salary & wages'), ('other', 'Other')], max_length=20)),
                ('vendor', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('itc_eligible', models.BooleanField(default=False)),
                ('bill_number', models.CharField(blank=True, default='', max_length=60)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('upi', 'UPI'), ('card', 'Card')], default='bank', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
