# Generated by Django 5.2.8 on 2026-10-02 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('model_label', models.CharField(max_length=100)),
                ('object_pk', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('preview_url', models.CharField(blank=True, default='', max_length=500)),
                ('payload', models.JSONField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at', '-id'],
            },
        ),
    ]
