# Generated by Django 5.2.8 on 2026-07-10 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_payment_status'),
        ('payments', '0003_alter_payment_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['received_at'], name='payments_pr_receive_dd7491_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('client', 'Client callback'), ('webhook', 'Webhook'), ('reconcile', 'Reconciliation job'), ('admin', 'Admin action'), ('system', 'System')], default='system', max_length=16)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('is_exception', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='payments_pa_created_93cf2e_idx'), models.Index(fields=['is_exception', 'resolved'], name='payments_pa_is_exce_ef7083_idx'), models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_a3a0f0_idx')],
            },
        ),
    ]
