# Generated by Django 5.2.8 on 2026-08-01 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_refund_ledger'),
        ('products', '0040_combo_derived_mrp_drop_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('variant_label', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='GST %% on this component at order time (snapshot).', max_digits=5)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='orders.orderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_components', to='products.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['order_item'], name='orders_orde_order_i_0f3748_idx')],
            },
        ),
    ]
