# Generated by Django 5.2.8 on 2026-08-04 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_line_hsn_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(help_text="Series this counter belongs to, e.g. 'NM/25-26' (one per FY).", max_length=16, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0, help_text='Highest number issued in this series so far.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, help_text="Full invoice number, e.g. 'NM/25-26/000123'. GST caps this at 16 characters (alphanumerics, '-' and '/' only).", max_length=16, unique=True)),
                ('series', models.CharField(db_index=True, help_text='Series the number was drawn from — one per financial year.', max_length=16)),
                ('sequence', models.PositiveIntegerField(help_text='Position within `series`. Continuous by construction.')),
                ('issued_at', models.DateTimeField(db_index=True, help_text='When the invoice was issued. The date printed on the bill.')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Grand total as invoiced (frozen copy of Order.total_amount).', max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, help_text='All output GST on the document: goods + delivery.', max_digits=10)),
                ('snapshot', models.JSONField(help_text='Everything the PDF prints, frozen at issue. See orders.invoicing.build_invoice_snapshot for the shape.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(help_text='The supply this invoice bills. PROTECTed: an order with an issued invoice is an accounting record and must not vanish.', on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['series', 'sequence'], name='orders_invo_series_4e8f40_idx')],
                'constraints': [models.UniqueConstraint(fields=('series', 'sequence'), name='uniq_invoice_series_sequence')],
            },
        ),
    ]
