# Generated by Django 5.2.8 on 2026-10-01 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_courier_name_order_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='place_of_supply_is_fallback',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('refund', 'Refund'), ('cancellation', 'Cancelled after invoice')], max_length=20)),
                ('number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('series', models.CharField(db_index=True, max_length=16)),
                ('sequence', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='orders.invoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='orders.order')),
                ('refund', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='orders.orderrefund')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('series', 'sequence'), name='uniq_credit_note_series_sequence')],
            },
        ),
    ]
