# Generated by Django 5.2.8 on 2026-10-01 18:45

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_email_verified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='purpose',
            field=models.CharField(choices=[('reset', 'Password reset'), ('verify', 'Email verification'), ('change_email', 'Change email')], default='reset', max_length=16),
        ),
    ]
