# Generated by Django 5.2.8 on 2026-07-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_chat_masala_dual_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Warn the admin (dashboard + daily digest) when stock falls to or below this.'),
        ),
    ]
