# Generated by Django 5.2.8 on 2026-07-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_productvariant_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombo',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert the admin when the number of combos that can still be built (limited by the scarcest component) falls to or below this.'),
        ),
    ]
